<html>
    <head>
        <title>Zend Framework jQuery AjaxLink Example</title>
        <script language="javascript"
                type="text/javascript"
                src="myCallbackFuncs.js"></script>
        <style type="text/css">
			/*demo page css*/
			body{ font: 62.5% "Trebuchet MS", sans-serif; margin: 50px;}
			#dialog_link {padding: .4em 1em .4em 20px;text-decoration: none;position: relative;}
			#dialog_link span.ui-icon {margin: 0 5px 0 0;position: absolute;left: .2em;top: 50%;margin-top: -8px;}
		
		</style>	
    </head>
 
    <body>
        <!-- without echoing jQuery this following -->
        <!-- list only prints a list of for links -->
    
		
			
		<p><a href="#" id="dialog_link" class="ui-state-default ui-corner-all"><span class="ui-icon ui-icon-newwin"></span>测试</a></p>
		
		测试


    </body>
</html>