ORZ_FIND(SAN_PROJECT SAN_PROJECT media/resources.cfg.in)
UNSET(SAN_PROJECT_BIN_DIR CACHE)
UNSET(SAN_PROJECT_INCLUDE_DIR CACHE)
UNSET(SAN_PROJECT_LIBRARY_DIR CACHE)
FILE(TO_CMAKE_PATH ${SAN_PROJECT_DIR}/media Media_DIR)
configure_file(${Media_DIR}/resources.cfg.in ${Media_DIR}/resources.cfg)
install(FILES ${Media_DIR}/resources.cfg  DESTINATION ./bin/debug)
install(FILES ${Media_DIR}/resources.cfg  DESTINATION ./bin/release)
install(DIRECTORY  ${SAN_PROJECT_DIR}/component/ DESTINATION ./bin/ )
