#ifndef __Orz_CodingComponentStableHeaders_h__
#define __Orz_CodingComponentStableHeaders_h__
#include <orz/Framework_Base/FrameworkBaseAllInclude.h>
#include <orz/Toolkit_Base/ToolkitBaseAllInclude.h>
#include <string>
#include <orz/Toolkit_Component_Task/Component/ComponentInterface.h>	
#include <orz/Toolkit_Component_Task/Component/Component.h>	
#include <orz/Toolkit_Component_Task/Component/ComponentFactories.h>
#include <orz/Toolkit_Tasks/TaskManager.h>
#include <Ogre/Ogre.h>
#include <orz/Toolkit_Component_Task/Component/ComponentQueryInterface.h>	
#include <orz/View_OGRE3D/OgreGraphicsManager.h>
#include <orz/View_CEGUI/CEGUIManager.h>
#include <orz/View_OIS/OISInputManager.h>
#include <orz/View_Fmod/FmodSoundManager.h>
#include <orz/Framework_Base/FrameworkBase.h>
#include <orz/Toolkit_Base/EventSystem/EventWorld.h>
#include <orz/View_OGRE3D/OgreUpdateInRenderingQueued.h>
#endif
